---
- name: Install IIS Web-Server with sub features and management tools
  ansible.windows.win_feature:
    name:
      - Web-Server
      - Web-Common-Http
    state: present
    restart: true
    include_sub_features: true
    include_management_tools: true
  register: win_feature
  tags:
    - install_iis
    - install_hiscout
